services:
  - type: web
    name: nestflo-market-intelligence
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: PIPELINE_BACKEND_URL
        sync: false
        value: ""
      - key: PIPELINE_API_KEY
        sync: false
        value: ""
