services:
  - type: web
    name: nestflo-market-intelligence
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: PIPELINE_BACKEND_URL
        value: "https://pipeline.hmo-market-intelligence.co.uk"
      - key: PIPELINE_API_KEY
        value: "nestflo-pipeline-key-2026"
