services:
  - type: web
    name: nestflo-market-intelligence
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
